version: '2'
services:
    smartisenprojectv2-app:
        image: smartisenprojectv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartisenprojectv2-mysql:3306/smartisenprojectv2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartisenprojectv2-mysql:
        extends:
            file: mysql.yml
            service: smartisenprojectv2-mysql
